# 基础设施服务配置
# 使用方法: docker-compose -f docker-compose.yml --env-file .env up -d

services:
  app:
    image: crpi-6a105b9464djyzkq.cn-chengdu.personal.cr.aliyuncs.com/jasonblog/blog:v20250611_010555
    container_name: blog-prod # 容器名称
    ports:
      - "3010:3010" # 端口映射：主机3000端口 -> 容器3000端口
    logging:
      driver: "json-file" # 使用 json-file 日志驱动
      options:
        max-size: "10m" # 单个日志文件最大 10MB
        max-file: "3" # 最多保留 3 个日志文件
    restart: unless-stopped # 容器异常退出时自动重启
